<a href="https://colab.research.google.com/github/anildemirel/anilldemirell/blob/main/CMPE302_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import modules
import matplotlib.pyplot as plt
import numpy as np

In [4]:
vec = [3,4,5,2]
s = 3

vec*s

[3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2]

In [5]:
vec =np.array([3,4,5,2])
s = 3

vec*s

array([ 9, 12, 15,  6])

In [6]:
#Assignment
# Create two vectors (2Dimensional vectors)
#Plot each vector
#Plot v1+v2, v1-v2, (v1*4 + v2/2)

In [7]:
#Dot Product
v1 = np.array([4,5,6,2])
v2 = np.array([-4,3,0,5])

np.dot(v1,v2)

9

In [10]:
v3 = np.array([-4,3,1,-2])
np.dot(v2,v3)

15

In [12]:
v4 = np.array([-4,3,1])
v5 = np.array([2,3,-1])

np.dot(v4,v5)

# vector v4 orthogonal to vector v5.

0

In [13]:
#Assignment 2
# 1) Come up with three 2Dimensional vectors, two of them are orthogonal, but neither is orthogonal to the third.
# 2) Plot all three vectors -- make sure the axes are square and equal.

In [14]:
#-----------------------
# Matrices

In [15]:
np.eye(3)
#it gives 3*3 identity matrices

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.zeros((3,4))
#it gives 3*4 zero matrices

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.full((5,2),7)

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [22]:
M = np.array ([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Assignment 3
# 1) Create 3 matrices: 2x2, 2x2, 3x2
# 2) Compute scalar matrix multiplication
# 3) add all pairs of matrices

In [26]:
#--------------
# Transposing a vector

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

transposed_M = np.transpose(M)

print(M)
print(transposed_M)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [24]:
#Symmetric Matrices
#.   is A = A^T

In [ ]:
# Assignment 4

# 1) What happens when transpose twice? M matrix, MT transpose, MTT
# 2) Confirm that transpose operation works on non-square matrices

In [30]:
#--------------------------
# Matrix Multiplication

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])

result_matrixMult = matrix1 @ matrix2
print(result_matrixMult)

[[ 58  64]
 [139 154]]


In [31]:
# Assignment 5

# 1) Create 3x3 matrix of integers
# 2) Multiply by (a) Identiy, (b) Zeros, (c) that matrix's transpose

In [32]:
#------------------------------
# The Matrix Inverse

matrix = np.array([[4, 7],
                   [2, 6]])

inverse_matrix = np.linalg.inv(matrix)

print(matrix)
print(inverse_matrix)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [36]:
#---------------------
# Eigenvalues and Eigenvectors
#
matrix = np.array([[4, -2],
                   [1,  1]])

# Compute Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)


print("Matrice:")
print(matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Matrice:
[[ 4 -2]
 [ 1  1]]

Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
